# Generated by Django 5.0.6 on 2024-09-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('user_email', models.EmailField(default=None, max_length=254, null=True)),
                ('object_type', models.CharField(max_length=100)),
                ('operation_type', models.SmallIntegerField(default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eventlogs',
            },
        ),
    ]
