# Generated by Django 5.0.6 on 2024-09-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventlogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="eventlog",
            table="eventlog",
        ),
    ]
