# Generated by Django 5.0.6 on 2024-09-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventlogs", "0002_alter_eventlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="eventlog",
            table="eventlogs",
        ),
    ]
