services:

  web:
    build: .

    restart: unless-stopped
    depends_on:
      broker:
        condition: service_started
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_value:/static/
      - media_value:/media/
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 400M
    networks:
      - glamp

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      web:
        condition: service_started
    ports:
      - '18180:80'
      - '443:443'
    volumes:

      - ./nginx/ssl:/etc/nginx/ssl:ro
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    # volumes:
    #   - ./nginx/cert:/etc/letsencrypt/
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    networks:
      - glamp


  broker:
    image: redis:latest
    restart: unless-stopped
    expose:
      - 6379
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    networks:
      - glamp

  celery-worker:
    build: .
    restart: unless-stopped
    command: bash -c "cd src/ && celery -A config.celery worker -l INFO"
    env_file:
      - .env
    depends_on: [broker, web]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M
    networks:
      - glamp

volumes:
  static_value:
  media_value:

networks:
  glamp:
    driver: bridge
configs:
  nginx_conf:
    file: ./nginx/default.conf

