services:
  db:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./commands:/commands
    ports:
      - 3306:3306
    networks:
      - glamp
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


#  eventlogs_db:
#    image: mysql:latest
#    env_file:
#      - .env
#    volumes:
#      - eventlogs_db_data:/var/lib/mysql
#    ports:
#      - 3307:3306
#    networks:
#      - glamp
#    depends_on:
#      - db
#    healthcheck:
#      test: [ "CMD-SHELL", "mysqladmin ping -h localhost || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  web:
    build: .
    volumes:
      - .:/app
      - static_value:/static/
      - media_value:/media/
    ports:
      - 8181:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - glamp

  broker:
    image: redis:latest
    ports:
      - 6379:6379
    depends_on:
      - db
    networks:
      - glamp

  celery-worker:
    build: .
    env_file:
      - .env
    command: bash -c "cd src/ && celery -A config.celery worker -l INFO"
    volumes:
      - .:/app
    depends_on:
      - db
      - broker
    networks:
      - glamp

#  celery-beat:
#    build: .
#    command: bash -c "cd src/ && celery -A config.celery beat --loglevel=info"
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    depends_on:
#      - db
#      - broker
#    networks:
#      - glamp

volumes:
  db_data:
  eventlogs_db_data:
  static_value:
  media_value:

networks:
  glamp:
    driver: bridge
