services:

  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      broker:
        condition: service_started
    ports:
      - "8181:8000"
    env_file:
      - .env
    volumes:
      - static_value:/static/
      - media_value:/media/
    networks:
      - glamp

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      web:
        condition: service_started  
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/cert:/etc/letsencrypt/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - glamp


  broker:
    image: redis:latest
    expose: [6379]
    networks:
      - glamp

  celery-worker:
    build: .
    command: bash -c "cd src/ && celery -A config.celery worker -l INFO"
    env_file:
      - .env
    depends_on: [broker, web]
    networks:
      - glamp

volumes:
  static_value:
  media_value:

networks:
  glamp:
    driver: bridge

