OPERATOR_MAPPING = {
    "$eq": "exact",
    "$eqi": "iexact",
    "$lt": "lt",
    "$lte": "lte",
    "$gt": "gt",
    "$gte": "gte",
    # "$in": "in",
    "$contains": "contains",
    "$icontains": "icontains",
    # "$null": "isnull",
    "$startsWith": "startswith",
    "$istartsWith": "istartswith",
    "$endsWith": "endswith",
    "$iendsWith": "iendswith",
}
