# Generated by Django 5.0.6 on 2024-09-26 19:02

import django.core.validators
import django.db.models.deletion
import glamp.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Вулиця')),
                ('house', models.CharField(max_length=255, verbose_name='Будинок')),
                ('apartment', models.CharField(blank=True, max_length=25, null=True, verbose_name='Апартаменти')),
                ('city', models.CharField(max_length=255, verbose_name='Mісто')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Oбласть')),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Довгота')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True, verbose_name='Назва Атрибуту')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибут',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to=glamp.utils.folder_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp'])], verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинка',
            },
        ),
        migrations.CreateModel(
            name='TypeGlamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True, verbose_name='Тип Глемпу')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Тип Глемпу',
                'verbose_name_plural': 'Типи Глемпу',
            },
        ),
        migrations.CreateModel(
            name='AttributeGlamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=225, verbose_name='Назва Атрибуту')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Додаткові Дані')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='glamp.attribute', verbose_name='Атрибут Глемпу')),
            ],
            options={
                'verbose_name': 'Атрибут Глемпу',
                'verbose_name_plural': 'Атрибут Глемпу',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Kатегорія')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='glamp.attributeglamp', verbose_name='Aтрибут')),
            ],
            options={
                'verbose_name': 'Kатегорія',
                'verbose_name_plural': 'Kатегорія',
            },
        ),
        migrations.CreateModel(
            name='Glamp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=225, unique=True, verbose_name='Назва Глемпу')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Опис')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Місткість')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Ціна за одну ніч', max_digits=10, null=True, verbose_name='Ціна')),
                ('status', models.PositiveSmallIntegerField(help_text='1: Незареєстрований, 2: Проходить Модерацію, 3: Активний, 4: Закритий', verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='glamp.address', verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Glamp',
                'verbose_name_plural': 'Glamp',
            },
        ),
    ]
